name = "jtsk2etrs"
uuid = "76835e4a-34ac-48d5-b86b-5685416fd123"
authors = ["Buday, Michal <buday2@gmail.com>"]
version = "0.1.0"

[deps]
Parsers = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
